// Code generated by protoc-gen-go. DO NOT EDIT.
// TODO: Regenerate with protoc when available:
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          internal/output/grpc/proto/cdc.proto
//
// Hand-written minimal stub for Phase 6 (protoc not available in build env).
// All exported types match what protoc would generate.

package proto

// SubscribeRequest is sent by the client to start a Subscribe streaming RPC.
type SubscribeRequest struct {
	ConsumerId string   // stable consumer identifier
	Tables     []string // empty = all tables (CFG-03)
	Operations []string // empty = all operations (CFG-04)
}

// ChangeEvent is streamed from server to client on the Subscribe RPC.
// The payload field carries the full JSON-encoded event (OUT-07 JSON fallback).
type ChangeEvent struct {
	Id             string // ULID string
	IdempotencyKey string
	Operation      string // insert | update | delete | read | control
	Table          string
	Payload        []byte // JSON-encoded kaptanto event.ChangeEvent
}

// AcknowledgeRequest is sent by the client to advance its durable cursor.
type AcknowledgeRequest struct {
	ConsumerId  string
	EventId     string // ULID of the last processed event
	PartitionId uint32
	Seq         uint64
}

// AcknowledgeResponse is returned by the Acknowledge RPC.
type AcknowledgeResponse struct {
	Ok bool
}
