// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// TODO: Regenerate with protoc when available (see cdc.pb.go for command).
//
// Hand-written minimal stub for Phase 6 (protoc not available in build env).

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// CdcStreamClient is the client API for CdcStream service.
type CdcStreamClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (CdcStream_SubscribeClient, error)
	Acknowledge(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*AcknowledgeResponse, error)
}

// CdcStream_SubscribeClient is the streaming client interface for Subscribe.
type CdcStream_SubscribeClient interface {
	Recv() (*ChangeEvent, error)
	grpc.ClientStream
}

// CdcStreamServer is the server API for CdcStream service.
type CdcStreamServer interface {
	Subscribe(*SubscribeRequest, CdcStream_SubscribeServer) error
	Acknowledge(context.Context, *AcknowledgeRequest) (*AcknowledgeResponse, error)
	mustEmbedUnimplementedCdcStreamServer()
}

// CdcStream_SubscribeServer is the streaming server interface for Subscribe.
type CdcStream_SubscribeServer interface {
	Send(*ChangeEvent) error
	Context() context.Context
	grpc.ServerStream
}

// UnimplementedCdcStreamServer must be embedded to have forward-compatible implementations.
type UnimplementedCdcStreamServer struct{}

func (UnimplementedCdcStreamServer) Subscribe(*SubscribeRequest, CdcStream_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedCdcStreamServer) Acknowledge(context.Context, *AcknowledgeRequest) (*AcknowledgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Acknowledge not implemented")
}
func (UnimplementedCdcStreamServer) mustEmbedUnimplementedCdcStreamServer() {}

// RegisterCdcStreamServer registers the CdcStreamServer implementation with the gRPC server.
func RegisterCdcStreamServer(s *grpc.Server, srv CdcStreamServer) {
	s.RegisterService(&CdcStream_ServiceDesc, srv)
}

// CdcStream_ServiceDesc is the grpc.ServiceDesc for CdcStream service.
var CdcStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kaptanto.v1.CdcStream",
	HandlerType: (*CdcStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Acknowledge",
			Handler:    _CdcStream_Acknowledge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _CdcStream_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cdc.proto",
}

func _CdcStream_Acknowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdcStreamServer).Acknowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaptanto.v1.CdcStream/Acknowledge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdcStreamServer).Acknowledge(ctx, req.(*AcknowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdcStream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CdcStreamServer).Subscribe(m, &cdcStreamSubscribeServer{stream})
}

type cdcStreamSubscribeServer struct {
	grpc.ServerStream
}

func (x *cdcStreamSubscribeServer) Send(m *ChangeEvent) error {
	return x.ServerStream.SendMsg(m)
}
