source: postgres://bench:bench@postgres:5432/bench
output: kafka
port: 7660
data-dir: /data
source-id: cluster_node2
cluster: true
cluster-dsn: postgres://bench:bench@postgres:5432/bench
cluster-peers:
  - nats:6222
tables:
  public.bench_events: {}
sinks:
  kafka:
    bootstrap-servers:
      - redpanda:9092
    topic-template: "{{.Schema}}.{{.Table}}"
